/**
 * Platform identifiers — our own canonical IDs, independent of any middleware.
 */
export const PLATFORM_IDS = {
  GA4: 'ga4',
  HUBSPOT: 'hubspot',
  META: 'meta',
  GOOGLE_ADS: 'google-ads',
  MAILCHIMP: 'mailchimp',
  KLAVIYO: 'klaviyo',
  LINKEDIN: 'linkedin',
  TIKTOK: 'tiktok',
  SNAPCHAT: 'snapchat',
  REDDIT: 'reddit',
  BING_ADS: 'bing-ads',
  SHOPIFY: 'shopify',
  TIKTOK_SHOP: 'tiktok-shop',
  LINKEDIN_PAGES: 'linkedin-pages',
  FACEBOOK_INSIGHTS: 'facebook-insights',
  INSTAGRAM_INSIGHTS: 'instagram-insights',
  TIKTOK_INSIGHTS: 'tiktok-insights',
  SALESFORCE: 'salesforce',
  X_ADS: 'x-ads',
  X_INSIGHTS: 'x-insights',
  WOOCOMMERCE: 'woocommerce',
  APPLOVIN: 'applovin',
  AHREFS: 'ahrefs',
  GOOGLE_SEARCH_CONSOLE: 'google-search-console',
} as const

export type PlatformId = (typeof PLATFORM_IDS)[keyof typeof PLATFORM_IDS]

export const PLATFORM_NAMES: Record<PlatformId, string> = {
  'ga4': 'Google Analytics 4',
  'hubspot': 'HubSpot',
  'meta': 'Meta Ads',
  'google-ads': 'Google Ads',
  'mailchimp': 'Mailchimp',
  'klaviyo': 'Klaviyo',
  'linkedin': 'LinkedIn Ads',
  'tiktok': 'TikTok Ads',
  'snapchat': 'Snapchat Ads',
  'reddit': 'Reddit Ads',
  'bing-ads': 'Microsoft Ads',
  'shopify': 'Shopify',
  'tiktok-shop': 'TikTok Shop',
  'linkedin-pages': 'LinkedIn Pages',
  'facebook-insights': 'Facebook Page Insights',
  'instagram-insights': 'Instagram Page Insights',
  'tiktok-insights': 'TikTok Page Insights',
  'salesforce': 'Salesforce',
  'x-ads': 'X Ads',
  'x-insights': 'X Profile Insights',
  'woocommerce': 'WooCommerce',
  'applovin': 'AppLovin',
  'ahrefs': 'Ahrefs',
  'google-search-console': 'Google Search Console',
}

export const PLATFORM_LOGOS: Record<PlatformId, string> = {
  'ga4': '/logos/platforms/ga4.svg',
  'hubspot': '/logos/platforms/hubspot.svg',
  'meta': '/logos/platforms/meta.svg',
  'google-ads': '/logos/platforms/google-ads.svg',
  'mailchimp': '/logos/platforms/mailchimp.svg',
  'klaviyo': '/logos/platforms/klaviyo.svg',
  'linkedin': '/logos/platforms/linkedin.svg',
  'tiktok': '/logos/platforms/tiktok.svg',
  'snapchat': '/logos/platforms/snapchat.svg',
  'reddit': '/logos/platforms/reddit.svg',
  'bing-ads': '/logos/platforms/bing-ads.svg',
  'shopify': '/logos/platforms/shopify.svg',
  'tiktok-shop': '/logos/platforms/tiktok.svg',
  'linkedin-pages': '/logos/platforms/linkedin.svg',
  'facebook-insights': '/logos/platforms/facebook.svg',
  'instagram-insights': '/logos/platforms/instagram.svg',
  'tiktok-insights': '/logos/platforms/tiktok.svg',
  'salesforce': '/logos/platforms/salesforce.svg',
  'x-ads': '/logos/platforms/x.svg',
  'x-insights': '/logos/platforms/x.svg',
  'woocommerce': '/logos/platforms/woocommerce.svg',
  'applovin': '/logos/platforms/applovin.svg',
  'ahrefs': '/logos/platforms/ahrefs.svg',
  'google-search-console': '/logos/platforms/google-search-console.svg',
}
